# Site settings
title: elkninja chronicles
description: Producing results, one query at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "elkninja.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author information
author:
  name: Eddie Mitchell
  email: eddie.mitchell@live.com

# Social media
twitter_username: emitch
github_username: elkninja
linkedin_username: emitch
email: eddie.mitchell@live.com

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink style
permalink: /:year/:month/:day/:title/

# Pagination (temporarily disabled)
# paginate: 5
# paginate_path: "/page/:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default layout for different types of content
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md
  - LICENSE.txt
  - .gitignore
  - docker-compose.yml
  - stage

# Sass settings
sass:
  style: compressed
  sass_dir: _sass
