title: elkninja chronicles
description: Producing results, one query at a time.
author: "Eddie Mitchell"

theme: minima

base_url: /elkninja.github.io
repository: elkninja/elkninja.github.io

# Minima social links
github_username: elkninja
linkedin_username: emitch
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
